pollsdemo/polls/urls.py
from django.conf.urls import url
from . import views

app_name = "polls"

urlpatterns = [
    url(r'^pollslist/$',views.Pollslist,name='pollslist'),
    url(r'^choice/(\d+)/$',views.Choice,name='choice'),
    url(r'^choicetool/(\d+)$',views.ChoiceTool,name='choicetool')

]

pollsdemo/pollsdemo/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^',include('polls.urls',namespace="polls"))
]

pollsdemo/polls/models.py
from django.db import models

# Create your models here.

class Options(models.Model):
    option = models.CharField(max_length=20)
    votes = models.IntegerField(max_length=255)
    oQuestion = models.ForeignKey('Questions',on_delete=models.CASCADE)

    def __str__(self):
        return self.option
    #更改后台列名显示
    def num(self):
        return self.votes
    num.short_description = "票数"

class Questions(models.Model):
    question = models.CharField(max_length=255)

    def __str__(self):
        return self.question

pollsdemo/polls/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from .models import Questions,Options
# Create your views here.


def Pollslist(request):
    list = Questions.objects.all()
    print(list,type(list))
    # return HttpResponse("列表页")
    return render(request,'polls/list.html',{'list':list})

def Choice(request,i):
    question = Questions.objects.get(pk = int(i))
    optlist = question.options_set.all()
    print(optlist,type(optlist))
    return render(request,'polls/choice.html',{'que':question,'optlist':optlist})

def ChoiceTool(request,i):
    opt = request.POST['options']
    question = Questions.objects.get(pk=int(i))
    optlist = question.options_set.all()
    thisopt = question.options_set.get(pk=int(opt))
    # print(thisopt,type(thisopt))
    thisopt.votes += 1
    thisopt.save()
    # return HttpResponse("投票成功")
    return render(request,'polls/votes.html',{'que':question,'optlist':optlist})

pollsdemo/templates/polls/choice.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>选择页</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class="connect">
        <h2>请选择</h2>
        <h3>{{que.question}}</h3>
        <form action="{% url 'polls:choicetool' que.id %}" method="post">
            {% for opt in optlist %}
                {{opt.option}}<input type="radio" value={{opt.id}} name="options"><br>
            {% empty %}
                <h3>暂无问题</h3>
            {% endfor %}
            <input type="submit" value="提交">
        </form>
        <a href="{% url 'polls:pollslist' %}">返回</a>
    </div>


</body>
</html>

pollsdemo/templates/polls/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页-调查列表</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class="connect">
        <h2>民意调查列表</h2>
        <ul>
            {% for que in list %}
                <li><a href="{% url 'polls:choice' que.id %}">{{que.id}}.{{que.question}}</a></li>
            {% empty %}
                <h3>暂无调查</h3>
            {% endfor %}
        </ul>

    </div>


</body>
</html>

pollsdemo/templates/polls/votes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>票数详情</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class="connect">
        <h3>{{que.question}}</h3>
        {% for opt in optlist %}
            {{opt.option}} {{opt.votes}}票  <br>
        {% empty %}
            <h3>暂无问题</h3>
        {% endfor %}
        <br><br>
        <a href="{% url 'polls:pollslist' %}">返回</a>
    </div>

</body>
</html>